feat:

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -55,7 +55,16 @@ jobs:
           host: ${{ secrets.EC2_HOST_NAME }}
           username: ${{ secrets.EC2_USER_NAME }}
           key: ${{ secrets.EC2_SSH_KEY }}
-          script: cd /var/www && git fetch --prune && git checkout main && git pull origin main
+          script: |
+            cd /var/www
+            if [ -d ".git" ]; then
+              git fetch --prune
+              git checkout main
+              git pull origin main
+            else
+              echo "Error: .git not found in /var/www"
+              exit 1
+            fi
 
     ############################ Frontend ############################
 
